name: CI

on:
  push:
    branches:
      - staging
      - 2-deploy-app

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Post init message
        run: echo "Pipeline initialized."
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 16
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'
    - name: Install Railway
      run: npm i -g @railway/cli
    - name: Deploy to Railway
      run: railway up --detach \
        --env B2_BUCKET_NAME="${{ secrets.GYMRATS_STAGING_IMG_B2_BUCKET_NAME }}" \
        --env B2_KEY_ID="${{ secrets.GYMRATS_STAGING_IMG_B2_KEY_ID }}" \
        --env B2_APPLICATION_KEY="${{ secrets.GYMRATS_STAGING_IMG_B2_APPLICATION_ID }}"
      env:
        RAILWAY_SERVICE_NAME: ${{ secrets.GYMRATS_STAGING_API_RAILWAY_SERVICE_NAME }}
        RAILWAY_TOKEN: ${{ secrets.GYMRATS_STAGING_API_RAILWAY_DEPLOY_TOKEN }}
        RAILWAY_DOCKERFILE_PATH: ../../docker/flask/Dockerfile
