name: CI

on:
  push:
    branches:
      - staging
      - test-terraform-with-railway

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Post init message
        run: echo "Pipeline initialized."
  terraform-deploy:
    needs: init
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3
    - name: Terraform Init
      run: terraform init
      working-directory: ./tf
    - name: Terraform Plan
      run: |
        terraform plan \
          --var="railway_token=${{ secrets.GYMRATS_STAGING_IMG_RAILWAY_TOKEN_TEST }}" \
          --var="github_repository=${{ github.repository }}" \
          --var="branch_name=${{ github.head_ref || github.ref_name }}"
      working-directory: ./tf
    - name: Terraform Apply
      run: |
        terraform apply -auto-approve \
          --var="railway_token=${{ secrets.GYMRATS_STAGING_IMG_RAILWAY_TOKEN_TEST }}" \
          --var="github_repository=${{ github.repository }}" \
          --var="branch_name=${{ github.head_ref || github.ref_name }}"
      working-directory: ./tf
