name: CI

on:
  push:
    branches:
      - staging
      - 2-deploy-app

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Post init message
        run: echo "Pipeline initialized."
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}
    steps:
    - uses: actions/checkout@v3
    - name: Use Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: pip install -Ur requirements.txt
    - name: Install Railway
      run: npm i -g @railway/cli
    - name: Deploy to Railway
      run: |
        railway variables set STORAGE_MODE "B2_STORAGE"
        railway variables set B2_BUCKET_NAME "${{ secrets.GYMRATS_STAGING_IMG_B2_BUCKET_NAME }}"
        railway variables set B2_KEY_ID "${{ secrets.GYMRATS_STAGING_IMG_B2_KEY_ID }}"
        railway variables set B2_APPLICATION_KEY "${{ secrets.GYMRATS_STAGING_IMG_B2_APPLICATION_KEY }}"
        railway up --service $RAILWAY_SERVICE_NAME
      env:
        RAILWAY_SERVICE_NAME: ${{ secrets.GYMRATS_STAGING_IMG_RAILWAY_SERVICE_NAME }}
        RAILWAY_TOKEN: ${{ secrets.GYMRATS_STAGING_IMG_RAILWAY_DEPLOY_TOKEN }}
        STORAGE_MODE: "B2_STORAGE"
        B2_BUCKET_NAME: ${{ secrets.GYMRATS_STAGING_IMG_B2_BUCKET_NAME }}
        B2_KEY_ID: ${{ secrets.GYMRATS_STAGING_IMG_B2_KEY_ID }}
        B2_APPLICATION_KEY: ${{ secrets.GYMRATS_STAGING_IMG_B2_APPLICATION_KEY }}
