name: CI

on:
  push:
    branches:
      - staging
      - test-terraform-with-railway

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Post init message
        run: echo "Pipeline initialized."
  terraform-deploy:
    needs: init
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3
    - name: Terraform Init
      run: terraform init
      working-directory: ./tf
    - name: Terraform Plan
      run: |
        terraform plan \
          --var="railway_token=${{ secrets.GYMRATS_STAGING_IMG_RAILWAY_TOKEN_TEST }}" \
          --var="github_repository=${{ github.repository }}" \
          --var="branch_name=${{ github.head_ref || github.ref_name }}" \
          --var="storage_mode=B2_STORAGE" \
          --var="b2_bucket_name=${{ secrets.GYMRATS_STAGING_IMG_B2_BUCKET_NAME }}" \
          --var="b2_key_id=${{ secrets.GYMRATS_STAGING_IMG_B2_KEY_ID }}" \
          --var="b2_application_key=${{ secrets.GYMRATS_STAGING_IMG_B2_APPLICATION_KEY }}"
      working-directory: ./tf
    - name: Terraform Apply
      run: |
        terraform apply -auto-approve \
          --var="railway_token=${{ secrets.GYMRATS_STAGING_IMG_RAILWAY_TOKEN_TEST }}" \
          --var="github_repository=${{ github.repository }}" \
          --var="branch_name=${{ github.head_ref || github.ref_name }}" \
          --var="storage_mode=B2_STORAGE" \
          --var="b2_bucket_name=${{ secrets.GYMRATS_STAGING_IMG_B2_BUCKET_NAME }}" \
          --var="b2_key_id=${{ secrets.GYMRATS_STAGING_IMG_B2_KEY_ID }}" \
          --var="b2_application_key=${{ secrets.GYMRATS_STAGING_IMG_B2_APPLICATION_KEY }}"
      working-directory: ./tf
    - name: Install Railway
      run: npm i -g @railway/cli
    - name: Deploy to Railway
      run: railway up --service $RAILWAY_SERVICE_NAME
      env:
        RAILWAY_SERVICE_NAME: ${{ secrets.GYMRATS_STAGING_IMG_RAILWAY_SERVICE_NAME }}
        RAILWAY_TOKEN: ${{ secrets.GYMRATS_STAGING_IMG_RAILWAY_DEPLOY_TOKEN }}
